-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 19:25:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel_db` ;

-- -----------------------------------------------------
-- Schema hotel_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_db` DEFAULT CHARACTER SET utf8 ;
USE `hotel_db` ;

-- -----------------------------------------------------
-- Table `hotel_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `role` ENUM('GUEST', 'CUSTOMER', 'MANAGER', 'ADMIN') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_db`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NOT NULL,
  `price_default` INT NOT NULL,
  `area` INT NOT NULL,
  `guests_capacity` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_db`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_db`.`room` (
  `room_number` INT NOT NULL,
  `category_id` INT NOT NULL,
  `current_status` ENUM('FREE', 'BOOKED', 'BUSY', 'UNAVAILABLE') NOT NULL,
  PRIMARY KEY (`room_number`, `category_id`),
  UNIQUE INDEX `room_number_UNIQUE` (`room_number` ASC) VISIBLE,
  INDEX `fk_room_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `hotel_db`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_db`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_db`.`application` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `category_title` VARCHAR(30) NOT NULL,
  `number_of_guests` INT NOT NULL,
  `check_in_date` DATETIME NOT NULL,
  `check_out_date` DATETIME NOT NULL,
  `current_status` VARCHAR(20) NOT NULL,
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`, `category_title`),
  INDEX `fk_application_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_application_category_idx` (`category_title` ASC) VISIBLE,
  CONSTRAINT `fk_application_category`
    FOREIGN KEY (`category_title`)
    REFERENCES `hotel_db`.`category` (`title`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_application_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `hotel_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_db`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_db`.`booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `number_of_guests` INT NOT NULL,
  `rooms_amount` INT NOT NULL,
  `check_in_date` DATETIME NOT NULL,
  `check_out_date` DATETIME NOT NULL,
  `processing_status` VARCHAR(30) NOT NULL,
  `total_price` INT NOT NULL,
  `payment_status` VARCHAR(45) NOT NULL,
  `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_booking_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_booking_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `hotel_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_db`.`booked_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_db`.`booked_rooms` (
  `booking_id` INT NOT NULL,
  `room_number` INT NOT NULL,
  INDEX `fk_booked_rooms_ room_number_idx` (`room_number` ASC) VISIBLE,
  INDEX `fk_booked_rooms_booking_idx` (`booking_id` ASC) VISIBLE,
  PRIMARY KEY (`booking_id`, `room_number`),
  CONSTRAINT `fk_booked_rooms_booking`
    FOREIGN KEY (`booking_id`)
    REFERENCES `hotel_db`.`booking` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booked_rooms_ room_number`
    FOREIGN KEY (`room_number`)
    REFERENCES `hotel_db`.`room` (`room_number`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_db`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_db`.`language` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_db`.`category_translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_db`.`category_translation` (
  `category_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `title` VARCHAR(30) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  INDEX `fk_category_translation_language_idx` (`language_id` ASC) VISIBLE,
  INDEX `fk_category_translation_categoty_idx` (`category_id` ASC) VISIBLE,
  PRIMARY KEY (`language_id`, `category_id`),
  CONSTRAINT `fk_category_translation_categoty`
    FOREIGN KEY (`category_id`)
    REFERENCES `hotel_db`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_translation_language`
    FOREIGN KEY (`language_id`)
    REFERENCES `hotel_db`.`language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
